import { describe, it, expect, beforeAll } from "vitest";
import os from "node:os";
import path from "node:path";
import fs from "node:fs";

/**
 * FALLBACK_AI_MEDIA migration — the load-bearing correctness claim, driven through the
 * REAL seedDefaults (not a re-implementation).
 *
 * A real operator was surprised by ~$40 of AI *video* generated by the real-footage
 * fallback. New installs default to images-only. A v1 migration had bumped EXISTING
 * installs to "both" (preserving pre-feature behaviour), but "both" reopens that exact
 * cost hole — so a v2 migration now resets the auto-set "both" back to "image", making
 * images-only the default for EVERYONE, while leaving a deliberate "video"/"image" pick
 * untouched.
 *
 * Each case manipulates the throwaway DB to the pre-seed state it wants, then calls the
 * actual seedDefaults() and asserts where the value lands.
 */
let settings!: typeof import("./settings");
let db!: typeof import("./db").default;

beforeAll(async () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), "fallback-media-"));
  process.env.FACELESS_STUDIO_DATA_DIR = dir;
  db = (await import("./db")).default;
  settings = await import("./settings");
});

/** Reset to a chosen pre-seed state: wipe settings + the migration flag, then optionally
 *  plant a row so the table is non-empty (an "existing install"). */
function resetTo(existing: boolean) {
  db.exec("DELETE FROM settings");
  if (existing) db.prepare("INSERT INTO settings (key, value) VALUES ('KIE_AI_MEDIA', 'image')").run();
}

describe("FALLBACK_AI_MEDIA default + migration (real seedDefaults)", () => {
  it("a brand-new install (empty settings table) defaults to images only", () => {
    resetTo(false);
    settings.seedDefaults();
    expect(settings.getSetting("FALLBACK_AI_MEDIA")).toBe("image");
  });

  it("an existing install is brought to images only too (v2 undoes the v1 'both' bump)", () => {
    // Policy: the default is now images-only for EVERYONE. v1 bumps an existing install to
    // "both" (pre-feature behaviour), then v2 immediately resets that auto-set "both" back
    // to "image" — the ~$40 AI-video surprise is closed for existing installs too.
    resetTo(true);
    settings.seedDefaults();
    expect(settings.getSetting("FALLBACK_AI_MEDIA")).toBe("image");
  });

  it("does not overwrite a value the operator has chosen", () => {
    // Migration is one-shot via its flag AND value-preserving: if a later run re-seeds, an
    // operator who picked "video" (or "image") keeps it.
    resetTo(true);
    settings.seedDefaults(); // migrates to "both", sets the flag
    db.prepare("UPDATE settings SET value = 'video' WHERE key = 'FALLBACK_AI_MEDIA'").run();
    settings.seedDefaults(); // second boot — must NOT clobber the choice
    expect(settings.getSetting("FALLBACK_AI_MEDIA")).toBe("video");
  });

  it("re-migrates correctly for a different install after the flag is cleared", () => {
    // Sanity that the flag — not luck — is what makes it one-shot: a fresh empty table
    // lands on "image".
    resetTo(false);
    settings.seedDefaults();
    expect(settings.getSetting("FALLBACK_AI_MEDIA")).toBe("image");
  });
});
